server:
  port: 8001
  servlet:
    # 用于后面实现路由转发
    context-path: "/member"

# 数据库连接
spring:
  datasource:
    url: jdbc:mysql://rm-bp18r10796l26616l4o.mysql.rds.aliyuncs.com/train_member?characterEncoding=UTF8&autoReconnect=true&serverTimezone=Asia/Shanghai
    username: train_member
    password: cptbtptq123ASDQW
    driver-class-name: com.mysql.cj.jdbc.Driver

# mybatis xml路径
mybatis:
  mapper-locations: classpath:/mapper/**/*.xml

# 更改mapper包日志级别
logging:
  level:
    org.xjydev.train.member.mapper: trace
